window.AigoWeather=(()=>{
  const cities={seoul:'서울',busan:'부산',incheon:'인천',daegu:'대구',daejeon:'대전',gwangju:'광주',ulsan:'울산',sejong:'세종',suwon:'수원',jeju:'제주'};
  let result=null,busy=false,message='',onWeather=()=>{},savedCity='',manual=false;
  try{savedCity=localStorage.getItem('aigo_weather_city')||'';}catch{}
  function paint(){const el=document.getElementById('live-weather');if(!el)return;el.innerHTML='<strong>지금 날씨에 맞춰 챙겨요</strong><p id="weather-status" class="sub" role="status"></p><div class="row"><button id="locate-weather">현재 위치로 확인</button><select id="weather-city" aria-label="날씨 지역" style="flex:1;width:130px"><option value="">지역 선택</option>'+Object.entries(cities).map(([k,v])=>`<option value="${k}" ${savedCity===k?'selected':''}>${v}</option>`).join('')+'</select><button id="refresh-weather">새로고침</button></div><p class="sub">위치 확인 시 약 10km 단위의 위치를 날씨 조회에만 전송하며 저장하지 않아요. 현재 날씨 기준이며 비 예보는 포함하지 않아요. <a href="https://openweathermap.org/" target="_blank" rel="noopener">OpenWeather</a></p>';
    document.getElementById('weather-status').textContent=busy?'날씨를 확인하고 있어요…':message||(result?`${cities[savedCity]||'현재 위치 주변'} · ${result.description} · ${result.temp}°C (체감 ${result.feelsLike}°C) · ${new Date(result.observedAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})} 관측${manual?' · 직접 선택 적용 중':''}`:'지역을 한 번 선택하면 다음부터 자동으로 확인해요.');
    document.getElementById('locate-weather').disabled=busy;document.getElementById('refresh-weather').disabled=busy;document.getElementById('weather-city').disabled=busy;
    document.getElementById('weather-city').onchange=e=>{savedCity=e.target.value;if(!savedCity)return;try{localStorage.setItem('aigo_weather_city',savedCity);}catch{}load('city='+savedCity);};
    document.getElementById('refresh-weather').onclick=()=>savedCity?load('city='+savedCity):locate();document.getElementById('locate-weather').onclick=locate;
  }
  async function load(query){if(busy)return;busy=true;message='';paint();try{const r=await fetch('/api/weather?'+query,{cache:'no-store',signal:AbortSignal.timeout(12000)});const v=await r.json();if(!r.ok)throw Error(v.error||'날씨 조회에 실패했어요.');if(!Array.isArray(v.conditions)||!Number.isFinite(v.temp))throw Error('날씨 응답을 확인하지 못했어요.');result=v;manual=false;onWeather(v.conditions.length?v.conditions.join('+'):'normal');}catch(e){message=e.name==='TimeoutError'?'날씨 응답이 늦어요. 다시 시도하거나 직접 선택해주세요.':e.message==='Failed to fetch'?'오프라인에서는 날씨를 직접 선택해주세요.':e.message;result=null;manual=true;onWeather('normal');}finally{busy=false;paint();}}
  function locate(){if(!navigator.geolocation){message='이 브라우저에서는 지역을 직접 선택해주세요.';paint();return;}message='위치 권한을 확인하고 있어요…';paint();navigator.geolocation.getCurrentPosition(pos=>{savedCity='';try{localStorage.removeItem('aigo_weather_city');}catch{}load('lat='+(Math.round(pos.coords.latitude*10)/10)+'&lon='+(Math.round(pos.coords.longitude*10)/10));},()=>{message='위치를 확인할 수 없어요. 지역을 선택해주세요.';paint();},{timeout:10000,maximumAge:600000,enableHighAccuracy:false});}
  return {mount(callback){onWeather=callback;paint();},init(){if(savedCity&&cities[savedCity])load('city='+savedCity);},manual(){manual=true;paint();}};
})();
